# Generated by Django 4.0.3 on 2022-04-02 23:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images/'),
        ),
    ]
