# Generated by Django 4.0.3 on 2022-04-03 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photos',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
