# Generated by Django 4.0.3 on 2022-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
